 BANK LOAN ANALYSIS  REPORT

 IMPORT LIBRARIES

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px

In [61]:
df=pd.read_excel(r"C:\Users\ELCOT\Downloads\financial_loan.xlsx")
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

#MetaData of data

In [10]:
print("No of Rows",df.shape[0])

No of Rows 38576

In [11]:
print("No of columns:",df.shape[1])

No of columns: 24

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  str
 2   application_type       38576 non-null  str
 3   emp_length             38576 non-null  str
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  str
 6   home_ownership         38576 non-null  str
 7   issue_date             38576 non-null  datetime64[us]
 8   last_credit_pull_date  38576 non-null  datetime64[us]
 9   last_payment_date      38576 non-null  datetime64[us]
 10  loan_status            38576 non-null  str
 11  next_payment_date      38576 non-null  datetime64[us]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  str
 14  sub_grade              38576 non-null  str
 15  term                   38576 non-null  str
 16  verification_status    38576 non-null  str
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[us](4), float64(4), int64(5), object(1), str(10)
memory usage: 7.1+ MB

 Data Types

In [14]:
df.dtypes

id                                int64
address_state                       str
application_type                    str
emp_length                          str
emp_title                        object
grade                               str
home_ownership                      str
issue_date               datetime64[us]
last_credit_pull_date    datetime64[us]
last_payment_date        datetime64[us]
loan_status                         str
next_payment_date        datetime64[us]
member_id                         int64
purpose                             str
sub_grade                           str
term                                str
verification_status                 str
annual_income                   float64
dti                             float64
installment                     float64
int_rate                        float64
loan_amount                       int64
total_acc                         int64
total_payment                     int64
dtype: object

In [16]:
df.describe()

,id,issue_date,last_credit_pull_date,last_payment_date,next_payment_date,member_id,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,38576,3.857600e+04,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.810371e+05,2021-07-16 02:31:35.562007,2021-06-08 13:36:34.193280,2021-06-26 09:52:08.909166,2021-07-26 20:42:20.605557,8.476515e+05,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
min,5.473400e+04,2021-01-01 00:00:00,2021-01-08 00:00:00,2021-01-08 00:00:00,2021-02-08 00:00:00,7.069900e+04,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,2021-04-11 00:00:00,2021-04-15 00:00:00,2021-03-16 00:00:00,2021-04-16 00:00:00,6.629788e+05,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,2021-07-11 00:00:00,2021-05-16 00:00:00,2021-06-14 00:00:00,2021-07-14 00:00:00,8.473565e+05,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,2021-10-11 00:00:00,2021-08-13 00:00:00,2021-09-15 00:00:00,2021-10-15 00:00:00,1.045652e+06,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000
max,1.077501e+06,2021-12-12 00:00:00,2022-01-20 00:00:00,2021-12-15 00:00:00,2022-01-15 00:00:00,1.314167e+06,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000,58564.000000
std,2.113246e+05,NaN,NaN,NaN,NaN,2.668105e+05,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777

In [17]:
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

  Toatal Loan Application

In [18]:
total_loan_application=df['id'].count()
print("Total Loan Application:",total_loan_application)

Total Loan Application: 38576

 MTD Total Loan Application

In [34]:
latest_date=df['issue_date'].max()
print(latest_date)
latest_year=latest_date.year
print(latest_year)
latest_month=latest_date.month
print(latest_month)

mtd_data=df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
print(mtd_data)

#filtering
mtd_loan_application=mtd_data['id'].count()
print(f"MTD Loan Application:(for {latest_date.strftime("%B %Y")}):{mtd_loan_application}")

2021-12-12 00:00:00
2021
12
            id address_state application_type emp_length  \
13     1020855            CA       INDIVIDUAL    5 years
15     1060995            RI       INDIVIDUAL   < 1 year
16     1046507            TX       INDIVIDUAL     1 year
18     1059497            FL       INDIVIDUAL  10+ years
42      472634            FL       INDIVIDUAL     1 year
...        ...           ...              ...        ...
38496  1026558            CA       INDIVIDUAL    4 years
38516   633392            CT       INDIVIDUAL  10+ years
38531  1052169            NY       INDIVIDUAL     1 year
38535   624384            MA       INDIVIDUAL    4 years
38546   634116            FL       INDIVIDUAL    6 years

                        emp_title grade home_ownership issue_date  \
13             henkel corporation     B           RENT 2021-12-11
15                        HSA-UWC     B           RENT 2021-12-11
16                    Child's Day     B           RENT 2021-12-02
18         Sandestin Beach Hilton     B       MORTGAGE 2021-12-12
42                        walmart     A           RENT 2021-12-09
...                           ...   ...            ...        ...
38496    ACCES I/O Products, Inc.     B       MORTGAGE 2021-12-11
38516                CVS Pharmacy     B            OWN 2021-12-10
38531           Binder and Binder     C           RENT 2021-12-11
38535     CH Newton Builders, Inc     C           RENT 2021-12-10
38546  Memorial Regional Hospital     E           RENT 2021-12-10

      last_credit_pull_date last_payment_date  ... sub_grade        term  \
13               2021-12-14        2021-12-14  ...        B5   36 months
15               2021-02-14        2021-10-13  ...        B4   36 months
16               2021-04-16        2021-12-14  ...        B1   36 months
18               2021-12-14        2021-12-14  ...        B2   36 months
42               2021-04-11        2021-11-10  ...        A1   36 months
...                     ...               ...  ...       ...         ...
38496            2021-10-14        2021-09-14  ...        B4   60 months
38516            2021-12-15        2021-01-16  ...        B5   60 months
38531            2021-01-12        2021-01-12  ...        C1   60 months
38535            2021-05-16        2021-04-15  ...        C4   60 months
38546            2021-12-15        2021-01-16  ...        E4   60 months

       verification_status annual_income     dti installment int_rate  \
13            Not Verified       48000.0  0.1533      268.36   0.1269
15         Source Verified       60000.0  0.0630      400.99   0.1242
16                Verified       16800.0  0.0350       98.29   0.0991
18                Verified       35000.0  0.1392      162.87   0.1065
42            Not Verified       12720.0  0.0000      231.75   0.0705
...                    ...           ...     ...         ...      ...
38496             Verified       54600.0  0.1209      561.44   0.1242
38516             Verified       40000.0  0.0885      149.98   0.1036
38531             Verified       50000.0  0.1922      460.10   0.1349
38535             Verified       43160.0  0.0189      229.33   0.1335
38546             Verified       30000.0  0.1280      186.64   0.1706

       loan_amount  total_acc  total_payment
13            8000         15           9661
15           12000         14           9547
16            3050          8           3538
18            5000         23           5863
42            7500          9           2073
...            ...        ...            ...
38496        25000         19          31693
38516         7000         21           8998
38531        20000         39          20226
38535        10000          5          13490
38546         7500          5          11198

[4314 rows x 24 columns]
MTD Loan Application:(for December 2021):4314

# Total Found Data

In [43]:
total_found_data=df['loan_amount'].sum()
print(total_found_data)
total_found_millions=total_found_data/1000000
print(f"Total Funded Amount: ${total_found_millions:.2f}M")

435757075
Total Funded Amount: $435.76M

MTD Total Found Data

In [44]:
latest_date=df['issue_date'].max()
print(latest_date)
latest_year=latest_date.year
print(latest_year)
latest_month=latest_date.month
print(latest_month)

mtd_data=df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
print(mtd_data)

mtd_total_fund_data=mtd_data['loan_amount'].sum()
mtd_total_funded_amount_millions=mtd_total_fund_data/100000
print(f"MTD Total Found Amount: {mtd_total_funded_amount_millions:.2f}M")

2021-12-12 00:00:00
2021
12
            id address_state application_type emp_length  \
13     1020855            CA       INDIVIDUAL    5 years
15     1060995            RI       INDIVIDUAL   < 1 year
16     1046507            TX       INDIVIDUAL     1 year
18     1059497            FL       INDIVIDUAL  10+ years
42      472634            FL       INDIVIDUAL     1 year
...        ...           ...              ...        ...
38496  1026558            CA       INDIVIDUAL    4 years
38516   633392            CT       INDIVIDUAL  10+ years
38531  1052169            NY       INDIVIDUAL     1 year
38535   624384            MA       INDIVIDUAL    4 years
38546   634116            FL       INDIVIDUAL    6 years

                        emp_title grade home_ownership issue_date  \
13             henkel corporation     B           RENT 2021-12-11
15                        HSA-UWC     B           RENT 2021-12-11
16                    Child's Day     B           RENT 2021-12-02
18         Sandestin Beach Hilton     B       MORTGAGE 2021-12-12
42                        walmart     A           RENT 2021-12-09
...                           ...   ...            ...        ...
38496    ACCES I/O Products, Inc.     B       MORTGAGE 2021-12-11
38516                CVS Pharmacy     B            OWN 2021-12-10
38531           Binder and Binder     C           RENT 2021-12-11
38535     CH Newton Builders, Inc     C           RENT 2021-12-10
38546  Memorial Regional Hospital     E           RENT 2021-12-10

      last_credit_pull_date last_payment_date  ... sub_grade        term  \
13               2021-12-14        2021-12-14  ...        B5   36 months
15               2021-02-14        2021-10-13  ...        B4   36 months
16               2021-04-16        2021-12-14  ...        B1   36 months
18               2021-12-14        2021-12-14  ...        B2   36 months
42               2021-04-11        2021-11-10  ...        A1   36 months
...                     ...               ...  ...       ...         ...
38496            2021-10-14        2021-09-14  ...        B4   60 months
38516            2021-12-15        2021-01-16  ...        B5   60 months
38531            2021-01-12        2021-01-12  ...        C1   60 months
38535            2021-05-16        2021-04-15  ...        C4   60 months
38546            2021-12-15        2021-01-16  ...        E4   60 months

       verification_status annual_income     dti installment int_rate  \
13            Not Verified       48000.0  0.1533      268.36   0.1269
15         Source Verified       60000.0  0.0630      400.99   0.1242
16                Verified       16800.0  0.0350       98.29   0.0991
18                Verified       35000.0  0.1392      162.87   0.1065
42            Not Verified       12720.0  0.0000      231.75   0.0705
...                    ...           ...     ...         ...      ...
38496             Verified       54600.0  0.1209      561.44   0.1242
38516             Verified       40000.0  0.0885      149.98   0.1036
38531             Verified       50000.0  0.1922      460.10   0.1349
38535             Verified       43160.0  0.0189      229.33   0.1335
38546             Verified       30000.0  0.1280      186.64   0.1706

       loan_amount  total_acc  total_payment
13            8000         15           9661
15           12000         14           9547
16            3050          8           3538
18            5000         23           5863
42            7500          9           2073
...            ...        ...            ...
38496        25000         19          31693
38516         7000         21           8998
38531        20000         39          20226
38535        10000          5          13490
38546         7500          5          11198

[4314 rows x 24 columns]
MTD Total Found Amount: 539.81M

Total Amount Received

In [45]:
total_amount_received=df['total_payment'].sum()
print(total_amount_received)
total_amount_received_millions=total_amount_received/1000000
print(f"Total Amount Received: ${total_amount_received_millions:.2f}M")

473070933
Total Amount Received: $473.07M

MTD Total Amount Received

In [46]:
latest_date=df['issue_date'].max()
print(latest_date)
latest_year=latest_date.year
print(latest_year)
latest_month=latest_date.month
print(latest_month)

mtd_data=df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
print(mtd_data)

mtd_total_received_data=mtd_data['total_payment'].sum()
mtd_total_amount_received_millions=mtd_total_received_data/100000
print(f"MTD Total Found Amount: {mtd_total_amount_received_millions:.2f}M")

2021-12-12 00:00:00
2021
12
            id address_state application_type emp_length  \
13     1020855            CA       INDIVIDUAL    5 years
15     1060995            RI       INDIVIDUAL   < 1 year
16     1046507            TX       INDIVIDUAL     1 year
18     1059497            FL       INDIVIDUAL  10+ years
42      472634            FL       INDIVIDUAL     1 year
...        ...           ...              ...        ...
38496  1026558            CA       INDIVIDUAL    4 years
38516   633392            CT       INDIVIDUAL  10+ years
38531  1052169            NY       INDIVIDUAL     1 year
38535   624384            MA       INDIVIDUAL    4 years
38546   634116            FL       INDIVIDUAL    6 years

                        emp_title grade home_ownership issue_date  \
13             henkel corporation     B           RENT 2021-12-11
15                        HSA-UWC     B           RENT 2021-12-11
16                    Child's Day     B           RENT 2021-12-02
18         Sandestin Beach Hilton     B       MORTGAGE 2021-12-12
42                        walmart     A           RENT 2021-12-09
...                           ...   ...            ...        ...
38496    ACCES I/O Products, Inc.     B       MORTGAGE 2021-12-11
38516                CVS Pharmacy     B            OWN 2021-12-10
38531           Binder and Binder     C           RENT 2021-12-11
38535     CH Newton Builders, Inc     C           RENT 2021-12-10
38546  Memorial Regional Hospital     E           RENT 2021-12-10

      last_credit_pull_date last_payment_date  ... sub_grade        term  \
13               2021-12-14        2021-12-14  ...        B5   36 months
15               2021-02-14        2021-10-13  ...        B4   36 months
16               2021-04-16        2021-12-14  ...        B1   36 months
18               2021-12-14        2021-12-14  ...        B2   36 months
42               2021-04-11        2021-11-10  ...        A1   36 months
...                     ...               ...  ...       ...         ...
38496            2021-10-14        2021-09-14  ...        B4   60 months
38516            2021-12-15        2021-01-16  ...        B5   60 months
38531            2021-01-12        2021-01-12  ...        C1   60 months
38535            2021-05-16        2021-04-15  ...        C4   60 months
38546            2021-12-15        2021-01-16  ...        E4   60 months

       verification_status annual_income     dti installment int_rate  \
13            Not Verified       48000.0  0.1533      268.36   0.1269
15         Source Verified       60000.0  0.0630      400.99   0.1242
16                Verified       16800.0  0.0350       98.29   0.0991
18                Verified       35000.0  0.1392      162.87   0.1065
42            Not Verified       12720.0  0.0000      231.75   0.0705
...                    ...           ...     ...         ...      ...
38496             Verified       54600.0  0.1209      561.44   0.1242
38516             Verified       40000.0  0.0885      149.98   0.1036
38531             Verified       50000.0  0.1922      460.10   0.1349
38535             Verified       43160.0  0.0189      229.33   0.1335
38546             Verified       30000.0  0.1280      186.64   0.1706

       loan_amount  total_acc  total_payment
13            8000         15           9661
15           12000         14           9547
16            3050          8           3538
18            5000         23           5863
42            7500          9           2073
...            ...        ...            ...
38496        25000         19          31693
38516         7000         21           8998
38531        20000         39          20226
38535        10000          5          13490
38546         7500          5          11198

[4314 rows x 24 columns]
MTD Total Found Amount: 580.74M

Average Interest Rate

In [ ]:
average_interest_rate=df['int_rate'].mean()*100
print(f"Average Int Rate:{average_interest_rate:.2f}M")

Average Int Rate:12.05M

Average Debt-to-Income Ratio(DTI)

In [ ]:
average_DTI_rate=df['dti'].mean()*100
print(f"Average DTI Rate:{average_DTI_rate:.2f}M")

Average DTI Rate:13.33M

Good Loan

In [59]:
good_loan=df[df['loan_status'].isin(["Fully Paid","Current"])]

total_loan_application=df['id'].count()

good_loan_application=good_loan['id'].count()
good_loan_funded_amounts=good_loan['loan_amount'].sum()
good_loan_received=good_loan['total_payment'].sum()

good_loan_found_amounts_millions=good_loan_funded_amounts/1000000
good_loan_received_millions=good_loan_received/1000000

good_loan_percentage=(good_loan_application/total_loan_application)*100

print(f"Good Loan Application:",good_loan_application)
print(f"Good Loan Funded Amount:{good_loan_found_amounts_millions:.2f}M")
print(f"Good Loan Received Amount:{good_loan_received_millions:.2f}M")
print(f"Good Loan Percentage:{good_loan_percentage:.2f}%")

Good Loan Application: 33243
Good Loan Funded Amount:370.22M
Good Loan Received Amount:435.79M
Good Loan Percentage:86.18%

Bad Loan

In [60]:
bad_loan=df[df['loan_status'].isin(["Charged Off"])]

total_loan_application=df['id'].count()

bad_loan_application=bad_loan['id'].count()
bad_loan_funded_amounts=bad_loan['loan_amount'].sum()
bad_loan_received=bad_loan['total_payment'].sum()

bad_loan_found_amounts_millions=bad_loan_funded_amounts/1000000
bad_loan_received_millions=bad_loan_received/1000000

bad_loan_percentage=(bad_loan_application/total_loan_application)*100

print(f"Bad Loan Application:",bad_loan_application)
print(f"Bad Loan Funded Amount:{bad_loan_found_amounts_millions:.2f}M")
print(f"Bad Loan Received Amount:{bad_loan_received_millions:.2f}M")
print(f"Bad Loan Percentage:{bad_loan_percentage:.2f}%")

Bad Loan Application: 5333
Bad Loan Funded Amount:65.53M
Bad Loan Received Amount:37.28M
Bad Loan Percentage:13.82%